/** Common dialing codes for waitlist phone capture. */
export const COUNTRY_CODES = [
  { code: "+1", label: "US / CA", flag: "🇺🇸" },
  { code: "+44", label: "UK", flag: "🇬🇧" },
  { code: "+61", label: "AU", flag: "🇦🇺" },
  { code: "+64", label: "NZ", flag: "🇳🇿" },
  { code: "+52", label: "MX", flag: "🇲🇽" },
  { code: "+33", label: "FR", flag: "🇫🇷" },
  { code: "+34", label: "ES", flag: "🇪🇸" },
  { code: "+39", label: "IT", flag: "🇮🇹" },
  { code: "+49", label: "DE", flag: "🇩🇪" },
  { code: "+31", label: "NL", flag: "🇳🇱" },
  { code: "+353", label: "IE", flag: "🇮🇪" },
  { code: "+351", label: "PT", flag: "🇵🇹" },
  { code: "+41", label: "CH", flag: "🇨🇭" },
  { code: "+46", label: "SE", flag: "🇸🇪" },
  { code: "+47", label: "NO", flag: "🇳🇴" },
  { code: "+45", label: "DK", flag: "🇩🇰" },
  { code: "+81", label: "JP", flag: "🇯🇵" },
  { code: "+82", label: "KR", flag: "🇰🇷" },
  { code: "+65", label: "SG", flag: "🇸🇬" },
  { code: "+852", label: "HK", flag: "🇭🇰" },
  { code: "+971", label: "AE", flag: "🇦🇪" },
  { code: "+91", label: "IN", flag: "🇮🇳" },
  { code: "+55", label: "BR", flag: "🇧🇷" },
  { code: "+54", label: "AR", flag: "🇦🇷" },
  { code: "+57", label: "CO", flag: "🇨🇴" },
  { code: "+56", label: "CL", flag: "🇨🇱" },
  { code: "+27", label: "ZA", flag: "🇿🇦" },
  { code: "+234", label: "NG", flag: "🇳🇬" },
  { code: "+254", label: "KE", flag: "🇰🇪" },
  { code: "+63", label: "PH", flag: "🇵🇭" },
] as const;

export const DEFAULT_COUNTRY_CODE = "+1";
