import type { JobListing } from "./types";

/**
 * Curated job listings (MD §4.7, Phase 1). Link-out aggregation with
 * attribution — we point at the source board, we don't scrape full postings.
 * Native postings are a later phase. Links go to the source board's Toronto
 * search since seed listings are illustrative.
 */
export const JOBS: JobListing[] = [
  {
    id: "j-sous-chef-yorkville",
    title: "Sous Chef",
    employer: "Yorkville fine-dining group",
    neighbourhood: "Yorkville",
    type: "BOH",
    employment: "Full-time",
    compensation: "$62k–$72k",
    source: "Culinary Agents",
    url: "https://culinaryagents.com/jobs?location=Toronto",
    postedAt: "2026-07-10T09:00:00Z",
  },
  {
    id: "j-line-cook-ossington",
    title: "Line Cook (Grill)",
    employer: "Ossington neighbourhood restaurant",
    neighbourhood: "Ossington",
    type: "BOH",
    employment: "Full-time",
    compensation: "$20–$24/hr",
    source: "Hcareers",
    url: "https://www.hcareers.ca/jobs/toronto-on",
    postedAt: "2026-07-09T14:00:00Z",
  },
  {
    id: "j-server-king-west",
    title: "Server",
    employer: "King West cocktail bar",
    neighbourhood: "King West",
    type: "FOH",
    employment: "Part-time",
    compensation: "Wage + tips",
    source: "Indeed",
    url: "https://ca.indeed.com/jobs?q=server&l=Toronto%2C+ON",
    postedAt: "2026-07-09T11:30:00Z",
  },
  {
    id: "j-bartender-entertainment",
    title: "Bartender",
    employer: "Entertainment District lounge",
    neighbourhood: "Entertainment District",
    type: "FOH",
    employment: "Full-time",
    compensation: "Wage + tips",
    source: "Culinary Agents",
    url: "https://culinaryagents.com/jobs?location=Toronto",
    postedAt: "2026-07-08T18:00:00Z",
  },
  {
    id: "j-gm-financial",
    title: "General Manager",
    employer: "Financial District restaurant",
    neighbourhood: "Financial District",
    type: "Management",
    employment: "Full-time",
    compensation: "$85k–$100k",
    source: "Hcareers",
    url: "https://www.hcareers.ca/jobs/toronto-on",
    postedAt: "2026-07-08T09:00:00Z",
  },
  {
    id: "j-pastry-little-italy",
    title: "Pastry Cook",
    employer: "Little Italy bakery-café",
    neighbourhood: "Little Italy",
    type: "BOH",
    employment: "Full-time",
    compensation: "$21–$25/hr",
    source: "Culinary Agents",
    url: "https://culinaryagents.com/jobs?location=Toronto",
    postedAt: "2026-07-07T07:30:00Z",
  },
  {
    id: "j-events-manager",
    title: "Private Events Manager",
    employer: "Waterfront event venue",
    neighbourhood: "Harbourfront",
    type: "Events",
    employment: "Full-time",
    compensation: "$60k–$70k",
    source: "Hcareers",
    url: "https://www.hcareers.ca/jobs/toronto-on",
    postedAt: "2026-07-06T15:00:00Z",
  },
  {
    id: "j-hotel-fb",
    title: "Food & Beverage Supervisor",
    employer: "Downtown hotel",
    neighbourhood: "Downtown Core",
    type: "Hotel",
    employment: "Full-time",
    compensation: "$52k–$58k",
    source: "Indeed",
    url: "https://ca.indeed.com/jobs?q=food+beverage+supervisor&l=Toronto%2C+ON",
    postedAt: "2026-07-06T10:00:00Z",
  },
  {
    id: "j-dishwasher-kensington",
    title: "Kitchen Porter / Dishwasher",
    employer: "Kensington Market wine bar",
    neighbourhood: "Kensington Market",
    type: "BOH",
    employment: "Part-time",
    compensation: "$17.50–$19/hr",
    source: "Indeed",
    url: "https://ca.indeed.com/jobs?q=dishwasher&l=Toronto%2C+ON",
    postedAt: "2026-07-05T13:00:00Z",
  },
  {
    id: "j-somm-midtown",
    title: "Sommelier",
    employer: "Midtown tasting-menu restaurant",
    neighbourhood: "Midtown",
    type: "FOH",
    employment: "Full-time",
    compensation: "Wage + tips",
    source: "Culinary Agents",
    url: "https://culinaryagents.com/jobs?location=Toronto",
    postedAt: "2026-07-05T09:00:00Z",
  },
];

export function getJobs(): JobListing[] {
  return [...JOBS].sort((a, b) => +new Date(b.postedAt) - +new Date(a.postedAt));
}
