/**
 * Curated Toronto accolade overlay (Michelin, Canada's 100 Best, local press).
 * Kept in sync with the frontend seed; merged onto live OSM data at ingest time.
 * This is the ONE thing OpenStreetMap can't provide.
 */
export type CuratedAccolade = { source: string; detail: string; year: number };

export type CuratedRestaurant = {
  id: string;
  slug: string;
  name: string;
  lat: number;
  lng: number;
  neighbourhood?: string;
  address?: string;
  cuisineTags: string[];
  priceLevel?: string;
  accolades: CuratedAccolade[];
  website?: string;
  instagram?: string;
  reservationUrl?: string;
  blurb?: string;
  featured?: boolean;
  claimedByUserId?: string | null;
};

export const CURATED: CuratedRestaurant[] = [
  {
    id: "r-sushi-masaki-saito",
    slug: "sushi-masaki-saito",
    name: "Sushi Masaki Saito",
    lat: 43.6708,
    lng: -79.3915,
    neighbourhood: "Yorkville",
    address: "88 Avenue Rd, Toronto, ON",
    cuisineTags: ["Japanese", "Sushi", "Omakase"],
    priceLevel: "$$$$",
    accolades: [
      { source: "Michelin", detail: "2 Stars", year: 2024 },
      { source: "Canada's 100 Best", detail: "Top 100", year: 2024 },
    ],
    website: "https://www.sushimasakisaito.com",
    blurb:
      "Toronto's only two-star omakase — an intimate Edomae counter led by chef Masaki Saito.",
    featured: true,
    claimedByUserId: null,
  },
  {
    id: "r-alo",
    slug: "alo",
    name: "Alo",
    lat: 43.6489,
    lng: -79.3969,
    neighbourhood: "Queen West",
    address: "163 Spadina Ave, Toronto, ON",
    cuisineTags: ["French", "Contemporary", "Tasting Menu"],
    priceLevel: "$$$$",
    accolades: [
      { source: "Michelin", detail: "1 Star", year: 2024 },
      { source: "Canada's 100 Best", detail: "Top 10", year: 2024 },
    ],
    website: "https://alorestaurant.com",
    blurb:
      "Patrick Kriss's flagship — refined French tasting menus that regularly top the national rankings.",
    featured: true,
    claimedByUserId: null,
  },
  {
    id: "r-restaurant-20-victoria",
    slug: "restaurant-20-victoria",
    name: "Restaurant 20 Victoria",
    lat: 43.6503,
    lng: -79.3767,
    neighbourhood: "Downtown Core",
    address: "20 Victoria St, Toronto, ON",
    cuisineTags: ["Contemporary", "Canadian", "Tasting Menu"],
    priceLevel: "$$$$",
    accolades: [
      { source: "Michelin", detail: "1 Star", year: 2024 },
      { source: "Canada's 100 Best", detail: "#1 in Canada", year: 2024 },
    ],
    website: "https://20victoria.ca",
    blurb:
      "Chef Julie Hyde's ingredient-driven counter — named Canada's best restaurant.",
    featured: true,
    claimedByUserId: null,
  },
  {
    id: "r-don-alfonso-1890",
    slug: "don-alfonso-1890",
    name: "Don Alfonso 1890",
    lat: 43.6465,
    lng: -79.3803,
    neighbourhood: "Financial District",
    address: "1 Adelaide St E, Toronto, ON",
    cuisineTags: ["Italian", "Fine Dining", "Seafood"],
    priceLevel: "$$$$",
    accolades: [{ source: "Michelin", detail: "1 Star", year: 2024 }],
    website: "https://donalfonso.ca",
    blurb: "Southern Italian grandeur high above the Financial District.",
    featured: true,
    claimedByUserId: null,
  },
  {
    id: "r-enigma",
    slug: "enigma-yorkville",
    name: "Enigma Yorkville",
    lat: 43.6712,
    lng: -79.3924,
    neighbourhood: "Yorkville",
    address: "8 Cumberland St, Toronto, ON",
    cuisineTags: ["Contemporary", "Tasting Menu"],
    priceLevel: "$$$$",
    accolades: [{ source: "Michelin", detail: "1 Star", year: 2024 }],
    website: "https://enigmayorkville.com",
    blurb: "A theatrical multi-course journey in the heart of Yorkville.",
    claimedByUserId: null,
  },
  {
    id: "r-edulis",
    slug: "edulis",
    name: "Edulis",
    lat: 43.6432,
    lng: -79.4025,
    neighbourhood: "Niagara",
    address: "169 Niagara St, Toronto, ON",
    cuisineTags: ["European", "Spanish", "Seafood"],
    priceLevel: "$$$",
    accolades: [
      { source: "Michelin", detail: "1 Star", year: 2024 },
      { source: "Canada's 100 Best", detail: "Top 100", year: 2024 },
    ],
    website: "https://edulisrestaurant.com",
    blurb:
      "Tobey Nemeth and Michael Caballo's seasonal, truffle-and-seafood-forward gem.",
    featured: true,
    claimedByUserId: null,
  },
  {
    id: "r-osteria-giulia",
    slug: "osteria-giulia",
    name: "Osteria Giulia",
    lat: 43.6797,
    lng: -79.3999,
    neighbourhood: "Yorkville",
    address: "134 Avenue Rd, Toronto, ON",
    cuisineTags: ["Italian", "Coastal"],
    priceLevel: "$$$",
    accolades: [{ source: "Michelin", detail: "1 Star", year: 2024 }],
    website: "https://osteriagiulia.com",
    blurb: "Coastal Italian cooking and a see-and-be-seen Avenue Rd room.",
    claimedByUserId: null,
  },
  {
    id: "r-quetzal",
    slug: "quetzal",
    name: "Quetzal",
    lat: 43.6588,
    lng: -79.3999,
    neighbourhood: "College West",
    address: "419 College St, Toronto, ON",
    cuisineTags: ["Mexican", "Wood-Fire"],
    priceLevel: "$$$",
    accolades: [{ source: "Michelin", detail: "1 Star", year: 2024 }],
    website: "https://quetzaltoronto.com",
    blurb: "Open-fire Mexican cooking anchored by an in-house masa program.",
    claimedByUserId: null,
  },
  {
    id: "r-shoushin",
    slug: "shoushin",
    name: "Shoushin",
    lat: 43.6883,
    lng: -79.4009,
    neighbourhood: "Midtown",
    address: "3328 Yonge St, Toronto, ON",
    cuisineTags: ["Japanese", "Sushi", "Omakase"],
    priceLevel: "$$$$",
    accolades: [{ source: "Michelin", detail: "1 Star", year: 2024 }],
    website: "https://shoushin.ca",
    blurb: "Precise Edomae omakase from chef Jackie Lin.",
    claimedByUserId: null,
  },
  {
    id: "r-prime-seafood-palace",
    slug: "prime-seafood-palace",
    name: "Prime Seafood Palace",
    lat: 43.6479,
    lng: -79.4197,
    neighbourhood: "Ossington",
    address: "955 Queen St W, Toronto, ON",
    cuisineTags: ["Steakhouse", "Seafood", "Canadian"],
    priceLevel: "$$$$",
    accolades: [
      { source: "Michelin", detail: "1 Star", year: 2024 },
      { source: "Canada's 100 Best", detail: "Top 50", year: 2024 },
    ],
    website: "https://primeseafoodpalace.com",
    blurb:
      "Matty Matheson's temple to dry-aged beef and seafood inside a soaring oak room.",
    featured: true,
    claimedByUserId: null,
  },
  {
    id: "r-aburi-hana",
    slug: "aburi-hana",
    name: "Aburi Hana",
    lat: 43.6706,
    lng: -79.3916,
    neighbourhood: "Yorkville",
    address: "102 Yorkville Ave, Toronto, ON",
    cuisineTags: ["Japanese", "Kaiseki"],
    priceLevel: "$$$$",
    accolades: [{ source: "Michelin", detail: "1 Star", year: 2024 }],
    website: "https://aburi.ca",
    blurb: "Kyoto-style kaiseki with a West Coast Aburi signature.",
    claimedByUserId: null,
  },
  {
    id: "r-frilu",
    slug: "frilu",
    name: "Frilu",
    lat: 43.8156,
    lng: -79.4085,
    neighbourhood: "Thornhill",
    address: "7713 Yonge St, Thornhill, ON",
    cuisineTags: ["Contemporary", "Tasting Menu"],
    priceLevel: "$$$$",
    accolades: [{ source: "Michelin", detail: "1 Star", year: 2024 }],
    website: "https://frilu.ca",
    blurb: "Chef John-Vincent Troiano's local, foraged tasting menus north of the city.",
    claimedByUserId: null,
  },
  {
    id: "r-canoe",
    slug: "canoe",
    name: "Canoe",
    lat: 43.6479,
    lng: -79.3813,
    neighbourhood: "Financial District",
    address: "66 Wellington St W, 54th Fl, Toronto, ON",
    cuisineTags: ["Canadian", "Fine Dining"],
    priceLevel: "$$$$",
    accolades: [
      { source: "Michelin", detail: "Selected", year: 2024 },
      { source: "Canada's 100 Best", detail: "Top 100", year: 2024 },
    ],
    website: "https://www.oliverbonacini.com/canoe",
    blurb: "Elevated Canadian cuisine 54 floors above Bay Street.",
    claimedByUserId: null,
  },
  {
    id: "r-richmond-station",
    slug: "richmond-station",
    name: "Richmond Station",
    lat: 43.6528,
    lng: -79.3796,
    neighbourhood: "Downtown Core",
    address: "1 Richmond St W, Toronto, ON",
    cuisineTags: ["Canadian", "Seasonal"],
    priceLevel: "$$$",
    accolades: [{ source: "Michelin", detail: "Bib Gourmand", year: 2024 }],
    website: "https://richmondstation.ca",
    blurb: "Carl Heinrich's beloved farm-to-table room and its cult Stn. Burger.",
    claimedByUserId: null,
  },
  {
    id: "r-bar-isabel",
    slug: "bar-isabel",
    name: "Bar Isabel",
    lat: 43.6555,
    lng: -79.4192,
    neighbourhood: "Little Italy",
    address: "797 College St, Toronto, ON",
    cuisineTags: ["Spanish", "Tapas", "Wine Bar"],
    priceLevel: "$$$",
    accolades: [
      { source: "Michelin", detail: "Selected", year: 2024 },
      { source: "Toronto Life", detail: "Best New Restaurant", year: 2014 },
    ],
    website: "https://barisabel.com",
    blurb: "Grant van Gameren's late-night Spanish landmark on College.",
    claimedByUserId: null,
  },
  {
    id: "r-bar-raval",
    slug: "bar-raval",
    name: "Bar Raval",
    lat: 43.6564,
    lng: -79.4128,
    neighbourhood: "Little Italy",
    address: "505 College St, Toronto, ON",
    cuisineTags: ["Spanish", "Pintxos", "Wine Bar"],
    priceLevel: "$$",
    accolades: [{ source: "BlogTO", detail: "Best Tapas", year: 2023 }],
    website: "https://www.thisisbarraval.com",
    blurb: "A Gaudí-inspired standing bar for pintxos and vermouth.",
    claimedByUserId: null,
  },
  {
    id: "r-buca",
    slug: "buca-king-west",
    name: "Buca",
    lat: 43.6438,
    lng: -79.4009,
    neighbourhood: "King West",
    address: "604 King St W, Toronto, ON",
    cuisineTags: ["Italian", "Nose-to-Tail"],
    priceLevel: "$$$",
    accolades: [{ source: "Canada's 100 Best", detail: "Top 100", year: 2020 }],
    website: "https://buca.ca",
    blurb: "Rob Gentile's design-forward Italian in a converted King West boiler room.",
    claimedByUserId: null,
  },
  {
    id: "r-byblos",
    slug: "byblos",
    name: "Byblos",
    lat: 43.6465,
    lng: -79.3893,
    neighbourhood: "Entertainment District",
    address: "11 Duncan St, Toronto, ON",
    cuisineTags: ["Mediterranean", "Middle Eastern"],
    priceLevel: "$$$",
    accolades: [{ source: "Toronto Life", detail: "Best New Restaurant", year: 2014 }],
    website: "https://byblostoronto.com",
    blurb: "Eastern-Mediterranean sharing plates in a buzzy Duncan St room.",
    claimedByUserId: null,
  },
  {
    id: "r-pai",
    slug: "pai-northern-thai",
    name: "Pai Northern Thai Kitchen",
    lat: 43.6479,
    lng: -79.3899,
    neighbourhood: "Entertainment District",
    address: "18 Duncan St, Toronto, ON",
    cuisineTags: ["Thai", "Northern Thai"],
    priceLevel: "$$",
    accolades: [{ source: "BlogTO", detail: "Best Thai", year: 2023 }],
    website: "https://www.paitoronto.com",
    blurb: "Nuit Regular's perennially packed khao soi destination.",
    claimedByUserId: null,
  },
  {
    id: "r-fat-pasha",
    slug: "fat-pasha",
    name: "Fat Pasha",
    lat: 43.6748,
    lng: -79.4088,
    neighbourhood: "Dupont",
    address: "414 Dupont St, Toronto, ON",
    cuisineTags: ["Middle Eastern", "Vegetarian-Friendly"],
    priceLevel: "$$",
    accolades: [{ source: "Michelin", detail: "Bib Gourmand", year: 2024 }],
    website: "https://www.fatpasha.com",
    blurb: "Anthony Rose's cauliflower-and-hummus Middle Eastern favourite.",
    claimedByUserId: null,
  },
  {
    id: "r-grey-gardens",
    slug: "grey-gardens",
    name: "Grey Gardens",
    lat: 43.6547,
    lng: -79.4008,
    neighbourhood: "Kensington Market",
    address: "199 Augusta Ave, Toronto, ON",
    cuisineTags: ["Contemporary", "Wine Bar", "Seafood"],
    priceLevel: "$$$",
    accolades: [{ source: "Michelin", detail: "Bib Gourmand", year: 2024 }],
    website: "https://greygardens.ca",
    blurb: "Jen Agg's wine-forward Kensington room of many happy oysters.",
    claimedByUserId: null,
  },
  {
    id: "r-dailo",
    slug: "dailo",
    name: "DaiLo",
    lat: 43.6553,
    lng: -79.4188,
    neighbourhood: "Little Italy",
    address: "503 College St, Toronto, ON",
    cuisineTags: ["Asian", "French-Chinese"],
    priceLevel: "$$$",
    accolades: [{ source: "Michelin", detail: "Bib Gourmand", year: 2024 }],
    website: "https://www.dailoto.com",
    blurb: "Chef Nick Liu's new-school Chinese — home of the famous fried watermelon.",
    claimedByUserId: null,
  },
  {
    id: "r-mimi-chinese",
    slug: "mimi-chinese",
    name: "Mimi Chinese",
    lat: 43.6699,
    lng: -79.3902,
    neighbourhood: "Yorkville",
    address: "265 Davenport Rd, Toronto, ON",
    cuisineTags: ["Chinese", "Regional Chinese"],
    priceLevel: "$$$",
    accolades: [{ source: "Michelin", detail: "Bib Gourmand", year: 2024 }],
    website: "https://www.mimichinese.com",
    blurb: "Glamorous cross-regional Chinese cooking that took the city by storm.",
    claimedByUserId: null,
  },
  {
    id: "r-skippa",
    slug: "skippa",
    name: "Skippa",
    lat: 43.6567,
    lng: -79.4157,
    neighbourhood: "Harbord Village",
    address: "379 Harbord St, Toronto, ON",
    cuisineTags: ["Japanese", "Sushi"],
    priceLevel: "$$$",
    accolades: [{ source: "Michelin", detail: "Bib Gourmand", year: 2024 }],
    website: "https://www.skippa.ca",
    blurb: "A tiny, personal Japanese counter from chef Kaori Kuroda.",
    claimedByUserId: null,
  },
  {
    id: "r-pukka",
    slug: "pukka",
    name: "Pukka",
    lat: 43.6807,
    lng: -79.4278,
    neighbourhood: "St. Clair West",
    address: "778 St Clair Ave W, Toronto, ON",
    cuisineTags: ["Indian", "Modern Indian"],
    priceLevel: "$$",
    accolades: [{ source: "Michelin", detail: "Bib Gourmand", year: 2024 }],
    website: "https://www.pukka.ca",
    blurb: "Refined, contemporary Indian cooking on St. Clair West.",
    claimedByUserId: null,
  },
  {
    id: "r-scaramouche",
    slug: "scaramouche",
    name: "Scaramouche",
    lat: 43.6825,
    lng: -79.4001,
    neighbourhood: "Midtown",
    address: "1 Benvenuto Pl, Toronto, ON",
    cuisineTags: ["French", "Fine Dining"],
    priceLevel: "$$$$",
    accolades: [{ source: "Canada's 100 Best", detail: "Top 100", year: 2022 }],
    website: "https://www.scaramoucherestaurant.com",
    blurb: "A special-occasion classic with skyline views and a legendary coconut cream pie.",
    claimedByUserId: null,
  },
  {
    id: "r-actinolite",
    slug: "actinolite",
    name: "Actinolite",
    lat: 43.6712,
    lng: -79.4267,
    neighbourhood: "Dovercourt",
    address: "971 Ossington Ave, Toronto, ON",
    cuisineTags: ["Contemporary", "Canadian", "Tasting Menu"],
    priceLevel: "$$$",
    accolades: [{ source: "Canada's 100 Best", detail: "Top 100", year: 2023 }],
    website: "https://www.actinoliterestaurant.com",
    blurb: "Justin Cournoyer's quietly ambitious Ontario-terroir tasting menu.",
    claimedByUserId: null,
  },
  {
    id: "r-piano-piano",
    slug: "piano-piano",
    name: "Piano Piano",
    lat: 43.6572,
    lng: -79.4102,
    neighbourhood: "Harbord Village",
    address: "88 Harbord St, Toronto, ON",
    cuisineTags: ["Italian", "Pizza", "Pasta"],
    priceLevel: "$$$",
    accolades: [{ source: "BlogTO", detail: "Best Italian", year: 2023 }],
    website: "https://www.pianopianotherestaurant.com",
    blurb: "Playful, pink-hued Italian from chef Victor Barry.",
    claimedByUserId: null,
  },
  {
    id: "r-aloette",
    slug: "aloette",
    name: "Aloette",
    lat: 43.6491,
    lng: -79.3969,
    neighbourhood: "Queen West",
    address: "163 Spadina Ave, Toronto, ON",
    cuisineTags: ["Bistro", "Canadian"],
    priceLevel: "$$",
    accolades: [{ source: "Michelin", detail: "Bib Gourmand", year: 2024 }],
    website: "https://aloetterestaurant.com",
    blurb: "Alo's ground-floor diner — home of a much-copied cheeseburger and lemon meringue.",
    claimedByUserId: null,
  },
  {
    id: "r-favorites-thai",
    slug: "favorites-thai",
    name: "Favorites Thai BBQ",
    lat: 43.6503,
    lng: -79.4232,
    neighbourhood: "Ossington",
    address: "1000 Dundas St W, Toronto, ON",
    cuisineTags: ["Thai", "BBQ"],
    priceLevel: "$$",
    accolades: [{ source: "Michelin", detail: "Bib Gourmand", year: 2024 }],
    website: "https://www.favoritesthaibbq.com",
    blurb: "Northeastern Thai grill and som tum near Trinity Bellwoods.",
    claimedByUserId: null,
  },
  {
    id: "r-adamson-barbecue",
    slug: "adamson-barbecue",
    name: "Adamson Barbecue",
    lat: 43.7106,
    lng: -79.3216,
    neighbourhood: "Leaside",
    address: "176 Wicksteed Ave, Toronto, ON",
    cuisineTags: ["BBQ", "Texas BBQ"],
    priceLevel: "$$",
    accolades: [{ source: "BlogTO", detail: "Best BBQ", year: 2023 }],
    website: "https://www.adamsonbarbecue.com",
    blurb: "Central-Texas-style brisket smoked over Ontario oak.",
    claimedByUserId: null,
  },
  {
    id: "r-khao-san-road",
    slug: "khao-san-road",
    name: "Khao San Road",
    lat: 43.6465,
    lng: -79.3924,
    neighbourhood: "Entertainment District",
    address: "11 Charlotte St, Toronto, ON",
    cuisineTags: ["Thai", "Street Food"],
    priceLevel: "$$",
    accolades: [{ source: "BlogTO", detail: "Best Thai", year: 2022 }],
    website: "https://www.khaosanroad.ca",
    blurb: "Bangkok street food and the khao soi that helped start the craze.",
    claimedByUserId: null,
  },
  {
    id: "r-lil-toronto",
    slug: "lil-toronto",
    name: "Lil' Bit Chinese & Thai",
    lat: 43.6659,
    lng: -79.3536,
    neighbourhood: "Riverside",
    address: "827 Queen St E, Toronto, ON",
    cuisineTags: ["Chinese", "Thai"],
    priceLevel: "$$",
    accolades: [{ source: "BlogTO", detail: "Best New Openings", year: 2024 }],
    website: "https://www.blogto.com/restaurants/",
    blurb: "East-end regional Chinese and Thai — a neighbourhood word-of-mouth hit.",
    claimedByUserId: null,
  },
  {
    id: "r-lambo",
    slug: "la-banane",
    name: "La Banane",
    lat: 43.6439,
    lng: -79.4189,
    neighbourhood: "Ossington",
    address: "227 Ossington Ave, Toronto, ON",
    cuisineTags: ["French", "Seafood", "Brasserie"],
    priceLevel: "$$$",
    accolades: [{ source: "Toronto Life", detail: "Best New Restaurant", year: 2017 }],
    website: "https://labanane.ca",
    blurb: "A glamorous French brasserie with a tableside seafood tower and Ziggy Stardust bombe.",
    claimedByUserId: null,
  },
  {
    id: "r-antler",
    slug: "antler",
    name: "Antler Kitchen & Bar",
    lat: 43.6497,
    lng: -79.4256,
    neighbourhood: "Dundas West",
    address: "1454 Dundas St W, Toronto, ON",
    cuisineTags: ["Canadian", "Game", "Seasonal"],
    priceLevel: "$$$",
    accolades: [{ source: "BlogTO", detail: "Best Canadian", year: 2022 }],
    website: "https://www.antlerkitchenbar.com",
    blurb: "Wild game and foraged Ontario ingredients on Dundas West.",
    claimedByUserId: null,
  },
];
