import type { ChefProfile, Inquiry, WaitlistEntry } from "./types";

// Beachhead metro is London (docs/01 wedge: "saturate one affluent, chef-dense metro").
// London is intentionally the densest city so the directory never looks empty.
export const BEACHHEAD = "London";

export const CITIES = ["London", "Los Angeles", "Miami", "New York"];

export const CUISINES = [
  "Italian",
  "Japanese",
  "French",
  "Modern British",
  "Mediterranean",
  "Plant-Based",
  "BBQ",
  "Indian",
  "Mexican",
  "Pan-Asian",
];

export const OCCASIONS = [
  "Dinner Party",
  "Birthday",
  "Anniversary",
  "Private Event",
];

// Real photos (Unsplash, free license) committed under public/gallery, keyed by
// the unique dish label so the gallery definitions below stay untouched.
const GALLERY_SRC: Record<string, string> = {
  "Cured trout, dill": "/gallery/jordan-trout.jpg",
  "Aged beef, bone marrow": "/gallery/jordan-beef.jpg",
  "Garden herb table": "/gallery/jordan-garden.jpg",
  "Plated dessert": "/gallery/jordan-dessert.jpg",
  "Charred hispi": "/gallery/amara-hispi.jpg",
  "Wild mushroom tart": "/gallery/amara-mushroom.jpg",
  "Citrus & fennel": "/gallery/amara-citrus.jpg",
  "Fresh tagliatelle": "/gallery/marco-tagliatelle.jpg",
  "Tortellini in brodo": "/gallery/marco-tortellini.jpg",
  "Nigiri selection": "/gallery/kenji-nigiri.jpg",
  Otoro: "/gallery/kenji-otoro.jpg",
  Chawanmushi: "/gallery/kenji-chawanmushi.jpg",
  "Mezze spread": "/gallery/fatima-mezze.jpg",
  "Lamb over fire": "/gallery/fatima-lamb.jpg",
  "Whole rib over coals": "/gallery/olivia-rib.jpg",
  "Charred leeks": "/gallery/olivia-leeks.jpg",
  "Smoked short rib": "/gallery/olivia-shortrib.jpg",
  "Handmade tortillas": "/gallery/diego-tortillas.jpg",
  "Mole negro": "/gallery/diego-mole.jpg",
  "Summer rolls": "/gallery/sophie-rolls.jpg",
  "Caramel pork": "/gallery/sophie-pork.jpg",
  "Crudo bar": "/gallery/isabella-crudo.jpg",
  "Lemon spaghetti": "/gallery/isabella-spaghetti.jpg",
  "Roast duck": "/gallery/tomas-duck.jpg",
};

function g(label: string, a: string, b: string) {
  return {
    id: label.toLowerCase().replace(/\W+/g, "-"),
    label,
    gradA: a,
    gradB: b,
    src: GALLERY_SRC[label],
  };
}

export const SEED_CHEFS: ChefProfile[] = [
  {
    id: "c-jordan-lee",
    slug: "jordan-lee",
    name: "Jordan Lee",
    headline: "Modern British tasting menus, sourced within 50 miles",
    bio: "Trained at The Ledbury, now cooking privately across London for the last six years. I build seasonal, produce-led menus for intimate dinners and celebrations — every plate finished in front of your guests.",
    city: "London",
    cuisines: ["Modern British", "French"],
    hourlyRate: 75,
    eventRate: 1400,
    yearsExperience: 11,
    founding: true,
    pro: true,
    approved: true,
    serviceAreas: [
      { city: "London", region: "Greater London", radiusMiles: 25 },
    ],
    gallery: [
      g("Cured trout, dill", "#fde68a", "#b45309"),
      g("Aged beef, bone marrow", "#fecaca", "#7f1d1d"),
      g("Garden herb table", "#bbf7d0", "#166534"),
      g("Plated dessert", "#e9d5ff", "#6b21a8"),
    ],
    menus: [
      {
        id: "m-jl-tasting",
        title: "Seven-course seasonal tasting",
        pricePerHead: 145,
        courses: [
          { name: "Snacks", description: "Three canapés, house sourdough, cultured butter" },
          { name: "Trout", description: "Cured trout, cucumber, dill oil" },
          { name: "Cep", description: "Roast cep, hazelnut, aged parmesan" },
          { name: "Turbot", description: "Line-caught turbot, mussel butter sauce" },
          { name: "Beef", description: "Dry-aged sirloin, bone marrow, watercress" },
          { name: "Pre-dessert", description: "Buttermilk, gooseberry" },
          { name: "Dessert", description: "Dark chocolate, malt, sea salt" },
        ],
      },
      {
        id: "m-jl-supper",
        title: "Relaxed three-course supper",
        pricePerHead: 85,
        courses: [
          { name: "Starter", description: "Burrata, heritage tomato, basil" },
          { name: "Main", description: "Slow lamb shoulder, anchovy, rosemary potatoes" },
          { name: "Dessert", description: "Brown butter tart, crème fraîche" },
        ],
      },
    ],
    certifications: [
      { type: "id", status: "verified", provider: "Persona", verifiedAt: "2026-05-02" },
      { type: "food-safety", status: "verified", provider: "CIEH L2", verifiedAt: "2026-04-18" },
      { type: "insurance", status: "verified", provider: "Public liability £5m", verifiedAt: "2026-04-20" },
      { type: "background-check", status: "verified", provider: "Checkr", verifiedAt: "2026-05-05" },
    ],
    reviews: [
      { id: "r1", author: "Eleanor M.", rating: 5, text: "Faultless from menu to clean-up. Our guests still talk about the turbot.", eventRef: "Anniversary dinner, 10 guests", date: "2026-06-01" },
      { id: "r2", author: "The Harcourt Estate", rating: 5, text: "We now use Jordan monthly. Reliable, discreet, exceptional.", eventRef: "Recurring estate dining", date: "2026-05-12" },
    ],
  },
  {
    id: "c-amara-okafor",
    slug: "amara-okafor",
    name: "Amara Okafor",
    headline: "Plant-based fine dining that converts the skeptics",
    bio: "Ex-Gauthier Soho. I cook entirely plant-based menus that don't announce themselves as plant-based — just dinner that happens to be vegan. Great for mixed dietary tables.",
    city: "London",
    cuisines: ["Plant-Based", "Mediterranean"],
    hourlyRate: 70,
    eventRate: 1100,
    yearsExperience: 9,
    founding: true,
    pro: true,
    approved: true,
    serviceAreas: [{ city: "London", region: "Greater London", radiusMiles: 30 }],
    gallery: [
      g("Charred hispi", "#bbf7d0", "#15803d"),
      g("Wild mushroom tart", "#fed7aa", "#9a3412"),
      g("Citrus & fennel", "#fef9c3", "#a16207"),
    ],
    menus: [
      {
        id: "m-ao-five",
        title: "Five-course plant tasting",
        pricePerHead: 110,
        courses: [
          { name: "Garden", description: "Raw & pickled vegetables, smoked almond" },
          { name: "Tart", description: "Wild mushroom, tarragon, truffle" },
          { name: "Hispi", description: "Charred cabbage, miso butter, sesame" },
          { name: "Celeriac", description: "Whole-roast celeriac, caper, parsley" },
          { name: "Dessert", description: "Olive oil cake, blood orange" },
        ],
      },
    ],
    certifications: [
      { type: "id", status: "verified", provider: "Persona", verifiedAt: "2026-05-10" },
      { type: "food-safety", status: "verified", provider: "CIEH L2", verifiedAt: "2026-03-01" },
      { type: "insurance", status: "pending" },
      { type: "background-check", status: "none" },
    ],
    reviews: [
      { id: "r3", author: "Priya R.", rating: 5, text: "Half the table was vegan, half weren't — everyone was stunned. Nobody missed the meat.", eventRef: "Birthday, 12 guests", date: "2026-05-28" },
    ],
  },
  {
    id: "c-marco-bianchi",
    slug: "marco-bianchi",
    name: "Marco Bianchi",
    headline: "Hand-rolled pasta and Emilia-Romagna classics, at your table",
    bio: "Born in Bologna, fifteen years in London kitchens. I roll every sheet of pasta in your home and cook the way my nonna did — generous, unfussy, deeply seasonal.",
    city: "London",
    cuisines: ["Italian"],
    hourlyRate: 65,
    eventRate: 950,
    yearsExperience: 15,
    founding: true,
    pro: false,
    approved: true,
    serviceAreas: [{ city: "London", region: "Greater London", radiusMiles: 20 }],
    gallery: [
      g("Fresh tagliatelle", "#fde68a", "#b45309"),
      g("Tortellini in brodo", "#fef3c7", "#92400e"),
    ],
    menus: [
      {
        id: "m-mb-feast",
        title: "Emilian feast (family style)",
        pricePerHead: 75,
        courses: [
          { name: "Antipasti", description: "Mortadella, gnocco fritto, pickles" },
          { name: "Primo", description: "Tagliatelle al ragù, 6-hour bolognese" },
          { name: "Secondo", description: "Cotoletta, roast potatoes, salsa verde" },
          { name: "Dolce", description: "Zabaglione, amaretti" },
        ],
      },
    ],
    certifications: [
      { type: "id", status: "verified", provider: "Persona", verifiedAt: "2026-02-11" },
      { type: "food-safety", status: "verified", provider: "CIEH L2", verifiedAt: "2026-02-11" },
      { type: "insurance", status: "verified", provider: "Public liability £2m", verifiedAt: "2026-02-12" },
      { type: "background-check", status: "none" },
    ],
    reviews: [
      { id: "r4", author: "James T.", rating: 5, text: "The ragù alone is worth it. Marco is a force of nature in the kitchen.", eventRef: "Dinner party, 8 guests", date: "2026-04-30" },
      { id: "r5", author: "Sofia L.", rating: 4, text: "Wonderful food, ran a little late but worth the wait.", eventRef: "Family celebration, 14 guests", date: "2026-03-15" },
    ],
  },
  {
    id: "c-kenji-watanabe",
    slug: "kenji-watanabe",
    name: "Kenji Watanabe",
    headline: "Edomae sushi and kaiseki, omakase in your home",
    bio: "Fifteen years behind the counter, including six in Tokyo. I bring market fish, my own knives, and a quiet, precise omakase experience to private tables of up to ten.",
    city: "London",
    cuisines: ["Japanese", "Pan-Asian"],
    hourlyRate: 110,
    eventRate: 1900,
    yearsExperience: 15,
    founding: false,
    pro: true,
    approved: true,
    serviceAreas: [{ city: "London", region: "Central London", radiusMiles: 15 }],
    gallery: [
      g("Nigiri selection", "#fecdd3", "#9f1239"),
      g("Otoro", "#fda4af", "#881337"),
      g("Chawanmushi", "#fef9c3", "#854d0e"),
    ],
    menus: [
      {
        id: "m-kw-omakase",
        title: "Omakase counter (in-home)",
        pricePerHead: 185,
        courses: [
          { name: "Sakizuke", description: "Seasonal opener" },
          { name: "Sashimi", description: "Three cuts, market fish" },
          { name: "Nigiri", description: "Twelve pieces, Edomae style" },
          { name: "Owan", description: "Clear seasonal broth" },
          { name: "Dessert", description: "Yuzu, matcha" },
        ],
      },
    ],
    certifications: [
      { type: "id", status: "verified", provider: "Persona", verifiedAt: "2026-01-22" },
      { type: "food-safety", status: "verified", provider: "CIEH L3", verifiedAt: "2026-01-22" },
      { type: "insurance", status: "verified", provider: "Public liability £5m", verifiedAt: "2026-01-25" },
      { type: "background-check", status: "verified", provider: "Checkr", verifiedAt: "2026-02-01" },
    ],
    reviews: [
      { id: "r6", author: "Family Office (confidential)", rating: 5, text: "We fly Kenji to our clients. Consistently world-class and utterly professional.", eventRef: "Private omakase, 8 guests", date: "2026-06-10" },
    ],
  },
  {
    id: "c-fatima-zahra",
    slug: "fatima-zahra",
    name: "Fatima Zahra",
    headline: "Levantine and North African feasting menus",
    bio: "Mezze-led, fire-cooked, generous menus drawing on Beirut, Marrakech and my grandmother's table. Brilliant for relaxed gatherings that go late.",
    city: "London",
    cuisines: ["Mediterranean", "Indian"],
    hourlyRate: 60,
    eventRate: 820,
    yearsExperience: 8,
    founding: true,
    pro: false,
    approved: true,
    serviceAreas: [{ city: "London", region: "Greater London", radiusMiles: 25 }],
    gallery: [
      g("Mezze spread", "#fde68a", "#a16207"),
      g("Lamb over fire", "#fecaca", "#7f1d1d"),
    ],
    menus: [
      {
        id: "m-fz-feast",
        title: "Levantine feasting table",
        pricePerHead: 68,
        courses: [
          { name: "Mezze", description: "Hummus, muhammara, labneh, flatbreads" },
          { name: "From the fire", description: "Lamb shoulder, chicken msakhan" },
          { name: "Sides", description: "Freekeh, fattoush, roast roots" },
          { name: "Sweet", description: "Knafeh, orange blossom" },
        ],
      },
    ],
    certifications: [
      { type: "id", status: "verified", provider: "Persona", verifiedAt: "2026-04-01" },
      { type: "food-safety", status: "verified", provider: "CIEH L2", verifiedAt: "2026-04-01" },
      { type: "insurance", status: "pending" },
      { type: "background-check", status: "none" },
    ],
    reviews: [
      { id: "r7", author: "Daniel K.", rating: 5, text: "The table looked like a painting. Food kept coming and it was all superb.", eventRef: "Birthday, 16 guests", date: "2026-05-20" },
    ],
  },
  {
    id: "c-olivia-grant",
    slug: "olivia-grant",
    name: "Olivia Grant",
    headline: "Live-fire cooking and smoked feasts",
    bio: "Asado, smoke and char. I cook over fire in gardens and on terraces across London — whole cuts, seasonal vegetables blackened over coals, nothing timid.",
    city: "London",
    cuisines: ["BBQ", "Modern British"],
    hourlyRate: 68,
    eventRate: 1050,
    yearsExperience: 7,
    founding: false,
    pro: true,
    approved: true,
    serviceAreas: [{ city: "London", region: "Greater London", radiusMiles: 30 }],
    gallery: [
      g("Whole rib over coals", "#fecaca", "#7f1d1d"),
      g("Charred leeks", "#bbf7d0", "#166534"),
      g("Smoked short rib", "#fed7aa", "#9a3412"),
    ],
    menus: [
      {
        id: "m-og-fire",
        title: "Open-fire feast",
        pricePerHead: 92,
        courses: [
          { name: "From the coals", description: "Grilled flatbread, burnt onion butter" },
          { name: "Vegetables", description: "Charred hispi, leeks, romesco" },
          { name: "Centrepiece", description: "Smoked rib of beef, chimichurri" },
          { name: "Dessert", description: "Fire-roasted plums, clotted cream" },
        ],
      },
    ],
    certifications: [
      { type: "id", status: "verified", provider: "Persona", verifiedAt: "2026-03-20" },
      { type: "food-safety", status: "verified", provider: "CIEH L2", verifiedAt: "2026-03-20" },
      { type: "insurance", status: "verified", provider: "Public liability £5m", verifiedAt: "2026-03-22" },
      { type: "background-check", status: "pending" },
    ],
    reviews: [
      { id: "r8", author: "Marcus W.", rating: 5, text: "Watched her cook the whole thing over fire in our garden. Theatre and brilliant food.", eventRef: "Summer party, 20 guests", date: "2026-06-05" },
    ],
  },
  // --- Other metros (thinner, to show multi-city directory + SEO scaling) ---
  {
    id: "c-diego-morales",
    slug: "diego-morales",
    name: "Diego Morales",
    headline: "Modern Mexican, masa made by hand",
    bio: "Oaxaca-born, LA-based. Heirloom corn nixtamalized in your kitchen, mole built over days, mezcal pairings on request.",
    city: "Los Angeles",
    cuisines: ["Mexican"],
    hourlyRate: 80,
    eventRate: 1200,
    yearsExperience: 12,
    founding: false,
    pro: true,
    approved: true,
    serviceAreas: [{ city: "Los Angeles", region: "LA County", radiusMiles: 30 }],
    gallery: [
      g("Handmade tortillas", "#fde68a", "#b45309"),
      g("Mole negro", "#fed7aa", "#7c2d12"),
    ],
    menus: [
      {
        id: "m-dm-tasting",
        title: "Maíz tasting",
        pricePerHead: 130,
        courses: [
          { name: "Antojitos", description: "Tetela, quesillo, salsa macha" },
          { name: "Mole", description: "Mole negro, heritage chicken" },
          { name: "Pescado", description: "Aguachile, market fish" },
          { name: "Postre", description: "Corn ice cream, cajeta" },
        ],
      },
    ],
    certifications: [
      { type: "id", status: "verified", provider: "Persona", verifiedAt: "2026-04-11" },
      { type: "food-safety", status: "verified", provider: "ServSafe", verifiedAt: "2026-04-11" },
      { type: "insurance", status: "verified", provider: "GL $2m", verifiedAt: "2026-04-12" },
      { type: "background-check", status: "verified", provider: "Checkr", verifiedAt: "2026-04-15" },
    ],
    reviews: [
      { id: "r9", author: "Carla S.", rating: 5, text: "The mole took three days and you could taste every hour of it.", eventRef: "Anniversary, 10 guests", date: "2026-05-18" },
    ],
  },
  {
    id: "c-sophie-nguyen",
    slug: "sophie-nguyen",
    name: "Sophie Nguyen",
    headline: "Pan-Asian sharing menus with a French backbone",
    bio: "Miami-based, classically French-trained, cooking the food of my Vietnamese family. Bright, herbal, built for sharing.",
    city: "Miami",
    cuisines: ["Pan-Asian", "French"],
    hourlyRate: 75,
    eventRate: 980,
    yearsExperience: 10,
    founding: false,
    pro: false,
    approved: true,
    serviceAreas: [{ city: "Miami", region: "Miami-Dade", radiusMiles: 25 }],
    gallery: [
      g("Summer rolls", "#bbf7d0", "#15803d"),
      g("Caramel pork", "#fed7aa", "#9a3412"),
    ],
    menus: [
      {
        id: "m-sn-share",
        title: "Sharing table",
        pricePerHead: 95,
        courses: [
          { name: "To start", description: "Summer rolls, green papaya, nuoc cham" },
          { name: "Middle", description: "Clay-pot caramel pork, charred greens" },
          { name: "Finish", description: "Pandan custard, coconut" },
        ],
      },
    ],
    certifications: [
      { type: "id", status: "verified", provider: "Persona", verifiedAt: "2026-03-30" },
      { type: "food-safety", status: "verified", provider: "ServSafe", verifiedAt: "2026-03-30" },
      { type: "insurance", status: "pending" },
      { type: "background-check", status: "none" },
    ],
    reviews: [
      { id: "r10", author: "Tom B.", rating: 5, text: "Fresh, vivid, and beautifully presented. Will book again.", eventRef: "Dinner party, 8 guests", date: "2026-05-02" },
    ],
  },
  {
    id: "c-isabella-rossi",
    slug: "isabella-rossi",
    name: "Isabella Rossi",
    headline: "Coastal Italian and crudo bars",
    bio: "New York-based. Amalfi-inspired menus, raw bars, and pasta finished tableside for downtown lofts and Hamptons houses alike.",
    city: "New York",
    cuisines: ["Italian", "Mediterranean"],
    hourlyRate: 90,
    eventRate: 1500,
    yearsExperience: 13,
    founding: false,
    pro: true,
    approved: true,
    serviceAreas: [{ city: "New York", region: "NYC + Hamptons", radiusMiles: 100 }],
    gallery: [
      g("Crudo bar", "#fecdd3", "#9f1239"),
      g("Lemon spaghetti", "#fef9c3", "#a16207"),
    ],
    menus: [
      {
        id: "m-ir-coastal",
        title: "Coastal tasting",
        pricePerHead: 160,
        courses: [
          { name: "Raw bar", description: "Oysters, crudo, citrus" },
          { name: "Pasta", description: "Spaghetti al limone, finished tableside" },
          { name: "Pesce", description: "Whole roasted branzino" },
          { name: "Dolce", description: "Lemon olive oil cake" },
        ],
      },
    ],
    certifications: [
      { type: "id", status: "verified", provider: "Persona", verifiedAt: "2026-02-28" },
      { type: "food-safety", status: "verified", provider: "ServSafe", verifiedAt: "2026-02-28" },
      { type: "insurance", status: "verified", provider: "GL $5m", verifiedAt: "2026-03-01" },
      { type: "background-check", status: "verified", provider: "Checkr", verifiedAt: "2026-03-05" },
    ],
    reviews: [
      { id: "r11", author: "Estate Mgr, Hamptons", rating: 5, text: "Our go-to for summer service. Polished and unflappable.", eventRef: "Recurring summer dining", date: "2026-06-12" },
    ],
  },
  // --- A pending/unapproved chef to exercise the admin queue ---
  {
    id: "c-tomas-novak",
    slug: "tomas-novak",
    name: "Tomáš Novák",
    headline: "Central European comfort, elevated",
    bio: "Just joined Brigade — profile awaiting review. Prague-trained, London-based, modern takes on the food I grew up with.",
    city: "London",
    cuisines: ["Modern British", "French"],
    hourlyRate: 55,
    eventRate: 720,
    yearsExperience: 6,
    founding: true,
    pro: false,
    approved: false,
    serviceAreas: [{ city: "London", region: "Greater London", radiusMiles: 20 }],
    gallery: [g("Roast duck", "#fed7aa", "#9a3412")],
    menus: [
      {
        id: "m-tn-supper",
        title: "Sunday supper",
        pricePerHead: 58,
        courses: [
          { name: "Start", description: "Potato dumplings, brown butter" },
          { name: "Main", description: "Slow duck, red cabbage" },
          { name: "Sweet", description: "Plum dumplings" },
        ],
      },
    ],
    certifications: [
      { type: "id", status: "pending" },
      { type: "food-safety", status: "verified", provider: "CIEH L2", verifiedAt: "2026-06-20" },
      { type: "insurance", status: "none" },
      { type: "background-check", status: "none" },
    ],
    reviews: [],
  },
];

export const SEED_INQUIRIES: Inquiry[] = [
  {
    id: "i-1001",
    chefSlug: "jordan-lee",
    status: "new",
    contactName: "Eleanor Whitmore",
    contactEmail: "eleanor.w@example.com",
    eventDate: "2026-07-19",
    guests: 10,
    location: "Notting Hill, London",
    budget: 1800,
    message: "Anniversary dinner for ten. Wondering about the seven-course tasting — two guests are pescatarian.",
    source: "public-form",
    createdAt: "2026-06-26T18:30:00Z",
  },
  {
    id: "i-1002",
    chefSlug: "jordan-lee",
    status: "quoted",
    contactName: "The Harcourt Estate",
    contactEmail: "manager@harcourt.example.com",
    eventDate: "2026-07-05",
    guests: 8,
    location: "Surrey",
    budget: 2200,
    message: "Monthly estate dinner. Same format as last time please.",
    source: "employer",
    createdAt: "2026-06-22T09:15:00Z",
    quote: {
      id: "q-1",
      lineItems: [
        { label: "Seven-course tasting × 8", amount: 1160 },
        { label: "Travel & sourcing", amount: 180 },
        { label: "Service & clean-up", amount: 160 },
      ],
      total: 1500,
      deposit: 450,
      sentAt: "2026-06-23T10:00:00Z",
    },
  },
  {
    id: "i-1003",
    chefSlug: "jordan-lee",
    status: "completed",
    contactName: "James Thornton",
    contactEmail: "jthornton@example.com",
    eventDate: "2026-06-01",
    guests: 10,
    location: "Hampstead, London",
    message: "Anniversary — booked the tasting. Everything was perfect.",
    source: "public-form",
    createdAt: "2026-05-10T14:00:00Z",
  },
  {
    id: "i-1004",
    chefSlug: "amara-okafor",
    status: "new",
    contactName: "Priya Raman",
    contactEmail: "priya.r@example.com",
    eventDate: "2026-08-02",
    guests: 12,
    location: "Islington, London",
    budget: 1400,
    message: "Mixed table, half vegan. Loved the photos — is the five-course available on a Saturday?",
    source: "public-form",
    createdAt: "2026-06-27T11:05:00Z",
  },
  {
    id: "i-1005",
    chefSlug: "kenji-watanabe",
    status: "booked",
    contactName: "Confidential (family office)",
    contactEmail: "pa@familyoffice.example.com",
    eventDate: "2026-07-12",
    guests: 8,
    location: "Mayfair, London",
    budget: 2500,
    message: "Omakase for eight, two guests no shellfish.",
    source: "employer",
    createdAt: "2026-06-18T16:40:00Z",
    quote: {
      id: "q-2",
      lineItems: [
        { label: "Omakase × 8", amount: 1480 },
        { label: "Market fish sourcing", amount: 320 },
        { label: "Service", amount: 100 },
      ],
      total: 1900,
      deposit: 700,
      sentAt: "2026-06-19T09:00:00Z",
      acceptedAt: "2026-06-20T12:00:00Z",
    },
  },
];

export const SEED_WAITLIST: WaitlistEntry[] = [
  { id: "w-1", name: "Nadia H.", email: "nadia@example.com", city: "London", role: "chef", createdAt: "2026-06-20T10:00:00Z" },
  { id: "w-2", name: "Greenfield Family Office", email: "ops@greenfield.example.com", city: "London", role: "buyer", createdAt: "2026-06-21T10:00:00Z" },
];
